library(pointblank)

agent <-
  create_agent(
    tbl = ~jan2020_oslo,
    actions = action_levels(
      warn_at = 0.05,
      stop_at = 0.10
    ),
    tbl_name = "jan2020_oslo",
    label = "Validation plan generated by `draft_validation()`."
  ) %>%
  # Expect that column `Vannlokalitet_kode` is of type: character
  col_is_character(
    columns = c("Vannlokalitet_kode")
  ) %>%
  # Expect that column `Vannlokalitetsnavn` is of type: character
  col_is_character(
    columns = c("Vannlokalitetsnavn")
  ) %>%
  # Expect that column `Betegnelse` is of type: character
  col_is_character(
    columns = c("Betegnelse")
  ) %>%
  # Expect that column `Type` is of type: character
  col_is_character(
    columns = c("Type")
  ) %>%
  # Expect that column `Aktivitet_id` is of type: character
  col_is_character(
    columns = c("Aktivitet_id")
  ) %>%
  # Expect that column `Aktivitet_navn` is of type: character
  col_is_character(
    columns = c("Aktivitet_navn")
  ) %>%
  # Expect that column `Oppdragsgiver` is of type: character
  col_is_character(
    columns = c("Oppdragsgiver")
  ) %>%
  # Expect that column `Oppdragstaker` is of type: character
  col_is_character(
    columns = c("Oppdragstaker")
  ) %>%
  # Expect that column `Parameter_id` is of type: character
  col_is_character(
    columns = c("Parameter_id")
  ) %>%
  # Expect that column `Parameter_navn` is of type: character
  col_is_character(
    columns = c("Parameter_navn")
  ) %>%
  # Expect that column `Parameter_casnr` is of type: character
  col_is_character(
    columns = c("Parameter_casnr")
  ) %>%
  # Expect that column `Medium_id` is of type: character
  col_is_character(
    columns = c("Medium_id")
  ) %>%
  # Expect that column `Medium_navn` is of type: character
  col_is_character(
    columns = c("Medium_navn")
  ) %>%
  # Expect that column `LatinskNavn_id` is of type: numeric
  col_is_numeric(
    columns = c("LatinskNavn_id")
  ) %>%
  # Expect that values in `LatinskNavn_id` should be between `0` and `48034`
  # col_vals_between(
  #   columns = c("LatinskNavn_id"),
  #   left = 0,
  #   right = 48034
  # ) %>%
  # Expect that column `VitenskapligNavn` is of type: character
  col_is_character(
    columns = c("VitenskapligNavn")
  ) %>%
  # Expect that column `Provetakmetode_id` is of type: character
  col_is_character(
    columns = c("Provetakmetode_id")
  ) %>%
  # Expect that column `Analysemetode_id` is of type: character
  col_is_character(
    columns = c("Analysemetode_id")
  ) %>%
  # Expect that column `Tid_provetak` is of type: character
  col_is_character(
    columns = c("Tid_provetak")
  ) %>%
  # Expect that column `Ovre_dyp` is of type: numeric
  col_is_numeric(
    columns = c("Ovre_dyp")
  ) %>%
  # Expect that values in `Ovre_dyp` should be between `0` and `68.5`
  # col_vals_between(
  #   columns = c("Ovre_dyp"),
  #   left = 0,
  #   right = 68.5,
  #   na_pass = TRUE
  # ) %>%
  # Expect that column `Nedre_dyp` is of type: numeric
  col_is_numeric(
    columns = c("Nedre_dyp")
  ) %>%
  # Expect that values in `Nedre_dyp` should be between `0` and `69.5`
  # col_vals_between(
  #   columns = c("Nedre_dyp"),
  #   left = 0,
  #   right = 69.5,
  #   na_pass = TRUE
  # ) %>%
  # Expect that column `DybdeEnhet` is of type: character
  col_is_character(
    columns = c("DybdeEnhet")
  ) %>%
  # Expect that column `Filtrert_Prove` is of type: character
  col_is_character(
    columns = c("Filtrert_Prove")
  ) %>%
  # Expect that column `UnntasKlassifisering` is of type: logical
  col_is_logical(
    columns = c("UnntasKlassifisering")
  ) %>%
  # Expect that column `Operator` is of type: character
  col_is_character(
    columns = c("Operator")
  ) %>%
  # Expect that column `Verdi` is of type: numeric
  col_is_numeric(
    columns = c("Verdi")
  ) %>%
  # Expect that values in `Verdi` should be between `-27.398` and `48840`
  # col_vals_between(
  #   columns = c("Verdi"),
  #   left = -27.398,
  #   right = 48840
  # ) %>%
  # Expect that column `Listenavn` is of type: logical
  col_is_logical(
    columns = c("Listenavn")
  ) %>%
  # Expect that column `Enhet` is of type: character
  col_is_character(
    columns = c("Enhet")
  ) %>%
  # Expect that column `Provenr` is of type: character
  col_is_character(
    columns = c("Provenr")
  ) %>%
  # Expect that column `Deteksjonsgrense` is of type: logical
  col_is_logical(
    columns = c("Deteksjonsgrense")
  ) %>%
  # Expect that column `Kvantifiseringsgrense` is of type: numeric
  col_is_numeric(
    columns = c("Kvantifiseringsgrense")
  ) %>%
  # Expect that values in `Kvantifiseringsgrense` should be between `0.005` and `25`
  # col_vals_between(
  #   columns = c("Kvantifiseringsgrense"),
  #   left = 0.005,
  #   right = 25,
  #   na_pass = TRUE
  # ) %>%
  # Expect that column `Opprinnelse` is of type: logical
  col_is_logical(
    columns = c("Opprinnelse")
  ) %>%
  # Expect that column `Ant_verdier` is of type: numeric
  col_is_numeric(
    columns = c("Ant_verdier")
  ) %>%
  # Expect that values in `Ant_verdier` should be between `1` and `288`
  # col_vals_between(
  #   columns = c("Ant_verdier"),
  #   left = 1,
  #   right = 288
  # ) %>%
  # Expect that column `Kommentar` is of type: character
  col_is_character(
    columns = c("Kommentar")
  ) %>%
  # Expect that column `Arkiv` is of type: character
  col_is_character(
    columns = c("Arkiv")
  ) %>%
  # Expect that column `Produktbeskrivelse` is of type: logical
  col_is_logical(
    columns = c("Produktbeskrivelse")
  ) %>%
  # Expect that column `UTM33 Ost (X)` is of type: numeric
  col_is_numeric(
    columns = c("UTM33 Ost (X)")
  ) %>%
  # Expect that values in `UTM33 Ost (X)` should be between `256082.2938` and `270967.4`
  # col_vals_between(
  #   columns = c("UTM33 Ost (X)"),
  #   left = 256082.2938,
  #   right = 270967.4
  # ) %>%
  # Expect that column `UTM33 Nord (Y)` is of type: numeric
  col_is_numeric(
    columns = c("UTM33 Nord (Y)")
  ) %>%
  # Expect that values in `UTM33 Nord (Y)` should be between `6639043.9233` and `6656872.4`
  # col_vals_between(
  #   columns = c("UTM33 Nord (Y)"),
  #   left = 6639043.9233,
  #   right = 6656872.4
  # ) %>%
  # Expect entirely distinct rows across `Vannlokalitet_kode, Vannlokalitetsnavn, Betegnelse, Type, Aktivitet_id, Aktivitet_navn, Oppdragsgiver, Oppdragstaker, Parameter_id, Parameter_navn, Parameter_casnr, Medium_id, Medium_navn, LatinskNavn_id, VitenskapligNavn, Provetakmetode_id, Analysemetode_id, Tid_provetak, Ovre_dyp, Nedre_dyp, DybdeEnhet, Filtrert_Prove, UnntasKlassifisering, Operator, Verdi, Listenavn, Enhet, Provenr, Deteksjonsgrense, Kvantifiseringsgrense, Opprinnelse, Ant_verdier, Kommentar, Arkiv, Produktbeskrivelse, UTM33 Ost (X), UTM33 Nord (Y)`
  rows_distinct(
    columns = c(
      "Vannlokalitet_kode",
      "Vannlokalitetsnavn",
      "Betegnelse",
      "Type",
      "Aktivitet_id",
      "Aktivitet_navn",
      "Oppdragsgiver",
      "Oppdragstaker",
      "Parameter_id",
      "Parameter_navn",
      "Parameter_casnr",
      "Medium_id",
      "Medium_navn",
      "LatinskNavn_id",
      "VitenskapligNavn",
      "Provetakmetode_id",
      "Analysemetode_id",
      "Tid_provetak",
      "Ovre_dyp",
      "Nedre_dyp",
      "DybdeEnhet",
      "Filtrert_Prove",
      "UnntasKlassifisering",
      "Operator",
      "Verdi",
      "Listenavn",
      "Enhet",
      "Provenr",
      "Deteksjonsgrense",
      "Kvantifiseringsgrense",
      "Opprinnelse",
      "Ant_verdier",
      "Kommentar",
      "Arkiv",
      "Produktbeskrivelse",
      "UTM33 Ost (X)",
      "UTM33 Nord (Y)"
    )
  ) %>%
  # Expect that column schemas match
  col_schema_match(
    schema = col_schema(
      Vannlokalitet_kode = "character",
      Vannlokalitetsnavn = "character",
      Betegnelse = "character",
      Type = "character",
      Aktivitet_id = "character",
      Aktivitet_navn = "character",
      Oppdragsgiver = "character",
      Oppdragstaker = "character",
      Parameter_id = "character",
      Parameter_navn = "character",
      Parameter_casnr = "character",
      Medium_id = "character",
      Medium_navn = "character",
      LatinskNavn_id = "numeric",
      VitenskapligNavn = "character",
      Provetakmetode_id = "character",
      Analysemetode_id = "character",
      Tid_provetak = "character",
      Ovre_dyp = "numeric",
      Nedre_dyp = "numeric",
      DybdeEnhet = "character",
      Filtrert_Prove = "character",
      UnntasKlassifisering = "logical",
      Operator = "character",
      Verdi = "numeric",
      Listenavn = "logical",
      Enhet = "character",
      Provenr = "character",
      Deteksjonsgrense = "logical",
      Kvantifiseringsgrense = "numeric",
      Opprinnelse = "logical",
      Ant_verdier = "numeric",
      Kommentar = "character",
      Arkiv = "character",
      Produktbeskrivelse = "logical",
      `UTM33 Ost (X)` = "numeric",
      `UTM33 Nord (Y)` = "numeric"
    )
  ) %>%
  interrogate()

agent
