<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Vannmiljø Pollutants - Arctic &amp; Marine • Vm2eData</title>
<script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.3.8/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.3.8/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet">
<link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet">
<script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><script src="vannmiljo-pollutants_files/libs/quarto-html/popper.min.js"></script><script src="vannmiljo-pollutants_files/libs/quarto-html/tippy.umd.min.js"></script><link href="vannmiljo-pollutants_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="vannmiljo-pollutants_files/libs/quarto-html/light-border.css" rel="stylesheet">
<script src="vannmiljo-pollutants_files/libs/quarto-contrib/glightbox/glightbox.min.js"></script><link href="vannmiljo-pollutants_files/libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="vannmiljo-pollutants_files/libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Vannmiljø Pollutants - Arctic &amp; Marine">
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-light" data-bs-theme="light" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">Vm2eData</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">0.0.0.9000</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="active nav-item"><a class="nav-link" href="../articles/index.html">Articles</a></li>
      </ul>
<ul class="navbar-nav">
<li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json">
</form></li>
      </ul>
</div>


  </div>
</nav><div class="container template-quarto">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">

      <h1>Vannmiljø Pollutants - Arctic &amp; Marine</h1>





      <div class="d-none name"><code></code></div>
    </div>






    <p>I’ve split some of the pollutant-specific exploration out to here, so it gets its own file.</p>
<p>Vannmiljø identifies four types of parameters in their data:</p>
<ul>
<li>Biologiske kvalitetselementer</li>
<li>Fysisk-kjemiske kvalitetselementer</li>
<li>Hydromorfologiske kvalitetselementer</li>
<li>Spesifikke forurensende stoffer (miljøgifter)</li>
</ul>
<p>As a rule, we are uninterested in the first three.</p>
<section class="section level2"><h2 id="pollutants-table">Pollutants Table<a class="anchor" aria-label="anchor" href="#pollutants-table"></a>
</h2>
<p>We can download a table of all the parameters considered pollutants from Vannmiljø’s <a href="https://vannmiljokoder.miljodirektoratet.no/parameter/sfs" class="external-link">code list site</a>.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">pollutants</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readxl.tidyverse.org/reference/read_excel.html" class="external-link">read_excel</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://here.r-lib.org/reference/here.html" class="external-link">here</a></span><span class="op">(</span><span class="st">"data"</span>, <span class="st">"raw"</span>, <span class="st">"vannmiljo"</span>, <span class="st">"Vannmiljø_Miljøgifter_2026-09-29.xlsx"</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">parameters</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html" class="external-link">unique</a></span><span class="op">(</span><span class="va">pollutants</span><span class="op">$</span><span class="va">Name</span><span class="op">)</span></span></code></pre></div>
</details>
</div>
<div>
<blockquote>
<p><strong>Norwegian Environmental Agency comments on pollutants data</strong></p>
<blockquote>
<p>Spesifikke forurensende stoffer omfatter et bredt spekter av organiske miljøgifter og tungmetaller. De er inndelt i «prioriterte stoffer» og «andre stoffer». De prioriterte stoffene omfatter 45 stoffer eller stoffgrupper (jf. EU-direktiv 2013/39/EU). Det er utarbeidet miljøkvalitetsstandarder (EQS) for disse stoffene, som danner utgangspunkt for klassifisering av kjemisk tilstand. Miljøgiftene gruppert under «andre stoffer» utgjør støtteparametre for klassifisering av økologisk tilstand i den grad det er utarbeidet EQS for disse.</p>
</blockquote>
<p><em>Machine Translation:</em> Specific pollutants cover a broad range of organic contaminants and heavy metals. They are divided into “priority substances” and “other substances”. The priority substances comprise 45 substances or groups of substances (cf. EU Directive 2013/39/EU). Environmental quality standards (EQS) have been developed for these substances, and form the basis for classifying chemical status. The contaminants grouped under “other substances” serve as supporting parameters for classifying ecological status, to the extent that EQS have been developed for them.</p>
<blockquote>
<p>NB! For tungmetallene er EQS basert på løste fraksjoner (ikke partikulært bundet). Dersom tungmetallene skal klassifiseres må de analyseres på filtrerte prøver.</p>
</blockquote>
<p><em>Machine Translation:</em> <em>Note!</em> For heavy metals, the EQS are based on dissolved fractions (not particle-bound). If heavy metals are to be classified, they must be analysed on filtered samples.</p>
<blockquote>
<p>For å gjøre søk på miljøgiftene lettere i kodeverket er både prioriterte og andre stoffer gruppert i stoffgrupper etter kjemisk sammensetning og egenskaper (PAH, PCB osv.) så langt det lar seg gjøre.</p>
</blockquote>
<p><em>Machine Translation:</em> To make searching for contaminants in the code list easier, both priority and other substances are grouped into substance groups by chemical composition and properties (PAH, PCB, etc.) as far as possible.</p>
<blockquote>
<p>Parameterkodene for spesifikke forurensende stoffer følger i det alt vesentlige systematikken til det internasjonale havforskningsrådet (ICES), se ICES Reference Codes (RECO). Der ICES ikke har definert noen kode er det laget nye koder. Disse er i stor grad basert på godt innarbeidede forkortelser på kjemiske stoffer eller lagt så nært opp til ICES systematikk som mulig.</p>
</blockquote>
<p><em>Machine Translation:</em> The parameter codes for specific pollutants largely follow the system of the International Council for the Exploration of the Sea (ICES); see the ICES Reference Codes (RECO). Where ICES has not defined a code, new codes have been created. These are largely based on well-established abbreviations of chemical substances, or kept as close to the ICES system as possible.</p>
<blockquote>
<p>Nedenfor finner du eksempler på ferdig utfylte importskjema for utvalgte kvalitetselementer. Legg merke til at det er obligatorisk å oppgi prøvenummer (en fritt valgt kode) dersom registreringene gjelder enkeltindivider av f.eks. fisk eller skalldyr. På den måten vet man hvilke stoffkonsentrasjoner som tilhører ett og samme individ. Dessuten vil man unngå mistanke om duplikate registreringer dersom det er registrert samme verdi for et stoff i flere individer på samme prøvetakingstidspunkt. Tilsvarende er det også obligatorisk å oppgi prøvenummer for registrering av bunndyr i marine sedimenter (bløtbunnundersøkelser) for å skille mellom parallelle grabbprøver.</p>
</blockquote>
<p><em>Machine Translation:</em> Below you will find examples of completed import forms for selected quality elements. Note that it is mandatory to provide a sample number (a freely chosen code) when the registrations concern individual specimens of, e.g., fish or shellfish. That way, it is clear which substance concentrations belong to one and the same individual. It also avoids suspicion of duplicate registrations if the same value has been recorded for a substance in several individuals at the same sampling time. Similarly, it is mandatory to provide a sample number when registering benthic fauna in marine sediments (soft-bottom surveys), to distinguish between parallel grab samples.</p>
</blockquote>
</div>
<p>Let’s take a quick look at the table:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html" class="external-link">glimpse</a></span><span class="op">(</span><span class="va">pollutants</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,716
Columns: 12
$ ParameterID          &lt;chr&gt; "HXCCPD", "TCMOB135", "CDFM", "DCBPO24", "BTBPTMC…
$ Name                 &lt;chr&gt; "Heksaklorsyklopentadien", "2,4,6-trikloranisol",…
$ Description          &lt;chr&gt; "1,2,3,4,5,5-heksaklorsyklopenta-1,3-dien_x000d_\…
$ CASnr                &lt;chr&gt; "77-47-4", "87-40-1", "75-45-6", "133-14-2", "673…
$ QualityElementTypeID &lt;chr&gt; "SFS", "SFS", "SFS", "SFS", "SFS", "SFS", "SFS", …
$ QualityElementID     &lt;chr&gt; "AST", "AST", "AST", "AST", "AST", "AST", "AST", …
$ QualityElementName   &lt;chr&gt; "Andre stoffer", "Andre stoffer", "Andre stoffer"…
$ SubGroupID           &lt;chr&gt; "OCL", "OCL", "OCL", "OCL", "ORG", "ORG", "PHT", …
$ SubGroupName         &lt;chr&gt; "Klororganiske forbindelser (OCL)", "Klororganisk…
$ ParameterID_VannNett &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ ParameterID_WISE     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ Prioritized          &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…</code></pre>
</div>
</div>
<p>So, we can see that this table already comes with some pretty useful metadata. We have priority substances, CAS codes, long names, short names, a system of mutually exclusive categories, and possibly some other IDs for other databases (e.g. WISE, VannNett).</p>
<section class="level2"><h3 id="chemical-pollutant-subgroups">Chemical Pollutant Subgroups<a class="anchor" aria-label="anchor" href="#chemical-pollutant-subgroups"></a>
</h3>
<p>Let’s look at chemical pollutant subgroups first - this is likely to give us the most useful insight into the structure of the data.</p>
<p><code>SubGroupName</code> splits substances as follows:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html" class="external-link">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span>
<span></span>
<span><span class="va">pollutants</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html" class="external-link">group_by</a></span><span class="op">(</span><span class="va">SubGroupName</span>, <span class="va">SubGroupID</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/reframe.html" class="external-link">reframe</a></span><span class="op">(</span></span>
<span>    n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html" class="external-link">n</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>    example <span class="op">=</span> <span class="fu"><a href="https://stringr.tidyverse.org/reference/str_flatten.html" class="external-link">str_flatten_comma</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sample.html" class="external-link">sample</a></span><span class="op">(</span><span class="va">Name</span>, size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html" class="external-link">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html" class="external-link">desc</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html" class="external-link">kable</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<table class="table caption-top">
<colgroup>
<col style="width: 23%">
<col style="width: 5%">
<col style="width: 1%">
<col style="width: 69%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">SubGroupName</th>
<th style="text-align: left;">SubGroupID</th>
<th style="text-align: right;">n</th>
<th style="text-align: left;">example</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Organiske forbindelser (ORG)</td>
<td style="text-align: left;">ORG</td>
<td style="text-align: right;">984</td>
<td style="text-align: left;">Oleinsyredietanolamid, 1,1’-(klorfenylmetylen)bis[4-metoksybenzen], 1,2-difluor-4-[4-[2-(4-propylsykloheksyl)etyl]sykloheksyl]benzen</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mikroplast (MPL)</td>
<td style="text-align: left;">MPL</td>
<td style="text-align: right;">460</td>
<td style="text-align: left;">Antall naturgummibaserte fragmenter &gt;1 mm, Antall polyfluorerte polymere fragmenter &gt;1 mm, Antall etylen-vinylacetatbaserte fibre 300 µm - 1 mm</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Klororganiske forbindelser (OCL)</td>
<td style="text-align: left;">OCL</td>
<td style="text-align: right;">271</td>
<td style="text-align: left;">Kvinmerac, Heksaklorfenylbisykloheptadien, Fenoprop</td>
</tr>
<tr class="even">
<td style="text-align: left;">Perfluorerte alkylerte substanser (PFAS)</td>
<td style="text-align: left;">PFA</td>
<td style="text-align: right;">174</td>
<td style="text-align: left;">Perfluor-2,5,8,10-tetrametyl-3,6,9-trioksaundekansyre (4x3-PFECA), 8:2 diPAP, Sum PFAS (EFSA 4)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Polysykliske aromatiske hydrokarboner (PAH)</td>
<td style="text-align: left;">PAH</td>
<td style="text-align: right;">125</td>
<td style="text-align: left;">C3-Fenantrener/antracener, 2-hydroksynaftalen, 2,6-dimetylnaftalen</td>
</tr>
<tr class="even">
<td style="text-align: left;">Legemidler (LEG)</td>
<td style="text-align: left;">LEG</td>
<td style="text-align: right;">92</td>
<td style="text-align: left;">Haloperidol (legemiddel), Ibuprofen (legemiddel), Orfenadrin (legemiddel)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Metaller (MET)</td>
<td style="text-align: left;">MET</td>
<td style="text-align: right;">86</td>
<td style="text-align: left;">Aluminium, Antimon, Krom (VI)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Polyklorerte bifenyler (PCB)</td>
<td style="text-align: left;">PCB</td>
<td style="text-align: right;">86</td>
<td style="text-align: left;">OH-PCB107, OH-PCB146, PCB33</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bromorganiske forbindelser (OBR)</td>
<td style="text-align: left;">OBR</td>
<td style="text-align: right;">66</td>
<td style="text-align: left;">Pentabrombenzen, Brommetan, 1-brom-4-(tribrommetyl)benzen</td>
</tr>
<tr class="even">
<td style="text-align: left;">Polybromerte difenyletere (PBDE)</td>
<td style="text-align: left;">BDE</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">PBDE183, PBDE47, PBDE49+71</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alkylfenoler (APH)</td>
<td style="text-align: left;">APH</td>
<td style="text-align: right;">47</td>
<td style="text-align: left;">4-n-Oktylfenol, 3-etylfenol, 2-etylfenol</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ftalater (PHT)</td>
<td style="text-align: left;">PHT</td>
<td style="text-align: right;">47</td>
<td style="text-align: left;">(2-ethylheksyl)hydrogenftalate, Monobutylftalate, Dinonylftalat</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Polyklorerte dibenzofuraner/dioksiner (PCDF/DD)</td>
<td style="text-align: left;">PDX</td>
<td style="text-align: right;">41</td>
<td style="text-align: left;">Sum PCDF, HpCDF (F134), 1,2,3,6,8/1,3,4,7,9-PeCDF</td>
</tr>
<tr class="even">
<td style="text-align: left;">Siloksaner (SIL)</td>
<td style="text-align: left;">SIL</td>
<td style="text-align: right;">31</td>
<td style="text-align: left;">F-D4a, Tetradekametylsykloheptasiloksan (D7), Dokosametyldekasiloxan (L10)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UV-filtere (UVF)</td>
<td style="text-align: left;">UVF</td>
<td style="text-align: right;">31</td>
<td style="text-align: left;">4-Metylbenzylidenkamfor, 2-(4-metoksy-2,2,6,6-tetrametylpiperidin-1-yl)etyl 4-oksopentanoat (Tinuvin 622), (E)-EHMC</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aminer (AMI)</td>
<td style="text-align: left;">AMI</td>
<td style="text-align: right;">29</td>
<td style="text-align: left;">N-Nitrosodiisononylamin, N-Nitrosodipropylamin dannende stoffer, N-nitrosopiperazin</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fosfororganiske flammehemmere (PFR)</td>
<td style="text-align: left;">PFR</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Sum TBP og TIBP, Tri(1,3-diklor-2-propyl) fosfat (TDCP), Tri-m-kresylfosfat (TmCrP)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Polybromerte bifenyler (PBB)</td>
<td style="text-align: left;">PBB</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">PBB209, PBB153, PBB101</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Klorerte flammehemmere (CFR)</td>
<td style="text-align: left;">CFR</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">1,2,3,4,7,7-Heksaklor-5-(2,4,6-tribromfenyl)bisyklo[2.2.1]hept-2-en, 1,2,3,4,7,7-Heksaklor-5-fenylbisyklo[2.2.1]hept-2-en, Dekloran 604</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tinnorganiske forbindelser (TIN)</td>
<td style="text-align: left;">TIN</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">Dioktyltinndiklorid, Trioktyltinnklorid, Trifenyltinn kation (TPhT)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Terfenyler (TPH)</td>
<td style="text-align: left;">TPH</td>
<td style="text-align: right;">12</td>
<td style="text-align: left;">m-terfenyl, cis-1,3-difenylsykloheksan, 1,4-disyckoheksylbenzen</td>
</tr>
<tr class="even">
<td style="text-align: left;">Grunnstoffer (GRS)</td>
<td style="text-align: left;">GRS</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">Dibrom, Jod-131, Selen</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">DagTest, DagTest, DagTest</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This is a lot of groups, and each group has a lot of members. There’s no obvious group to pick on as the most relevant. We can take a quick look at the prioritised members of each group:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">pollutants</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">QualityElementName</span> <span class="op">==</span> <span class="st">"Prioriterte stoffer"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html" class="external-link">group_by</a></span><span class="op">(</span><span class="va">SubGroupName</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/reframe.html" class="external-link">reframe</a></span><span class="op">(</span>priority_substances <span class="op">=</span> <span class="fu"><a href="https://stringr.tidyverse.org/reference/str_flatten.html" class="external-link">str_flatten_comma</a></span><span class="op">(</span><span class="va">Name</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html" class="external-link">kable</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<table class="table caption-top">
<colgroup>
<col style="width: 9%">
<col style="width: 90%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">SubGroupName</th>
<th style="text-align: left;">priority_substances</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alkylfenoler (APH)</td>
<td style="text-align: left;">4-n-Nonylfenol, 4-tert-Oktylfenol, 4-iso-Nonylfenol</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bromorganiske forbindelser (OBR)</td>
<td style="text-align: left;">Sum Heksbromsyklododekan (HBCDD), 1,3,5,7,9,11-HBCDD, 1,2,5,6,9,10-HBCDD, a-HBCDD, b-HBCDD, g-HBCDD</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ftalater (PHT)</td>
<td style="text-align: left;">Bis(2-etylheksyl)ftalat</td>
</tr>
<tr class="even">
<td style="text-align: left;">Klororganiske forbindelser (OCL)</td>
<td style="text-align: left;">Pentaklorbenzen, Kortkjedete klorparafiner (C10-13), Sum DDT, Triklormetan, 1,1,2,2-Tetrakloreten, Sum triklorbenzener (alle isomere), 1,1,2-Trikloreten, Karbontetraklorid, Klorfenvinfos, Klorpyrifos, 1,2-dikloretan, Diklormetan, Diuron, pp’-DDT, Dicofol, Dieldrin, Endrin, Endosulfan, Heksaklorbenzen, Heksaklorbutadien, Sum HCH (må spesifiseres), Isodrin, Pentaklorfenol, Alaklor, Aldrin, Heptaklor, Heptaklorepoksid, Quinoxyfen, Aklonifen, Bifenox, Diklorvos</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Metaller (MET)</td>
<td style="text-align: left;">Kadmium, Kvikksølv, Nikkel, Bly</td>
</tr>
<tr class="even">
<td style="text-align: left;">Organiske forbindelser (ORG)</td>
<td style="text-align: left;">Simazin, Trifluralin, Isoproturon, Irgarol, Atrazin, Benzen, Terbutryn, Cypermetrin, alfa-Cypermetrin, Alfametrin, 8-[4-(4-metylfenyl-)-3-sykloheksen1-yl]-1,4-Dioksaspiro[4.5]decan</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Perfluorerte alkylerte substanser (PFAS)</td>
<td style="text-align: left;">Perfluoroktansulfonsyre (PFOS)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Polybromerte difenyletere (PBDE)</td>
<td style="text-align: left;">PBDE100, PBDE153, PBDE154, PBDE28, PBDE47, PBDE99, Sum PBDE6, Sum HeptaBDE, Sum TetraBDE, Sum HeksaBDE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Polyklorerte bifenyler (PCB)</td>
<td style="text-align: left;">PCB126, PCB156, PCB169, PCB77, PCB105, PCB118, PCB81, PCB114, PCB123, PCB157, PCB167, PCB189</td>
</tr>
<tr class="even">
<td style="text-align: left;">Polyklorerte dibenzofuraner/dioksiner (PCDF/DD)</td>
<td style="text-align: left;">TCDD (D48), PeCDD (D54), HxCDD (D66), HpCDD (D73), HxCDD (D67), HxCDD (D70), OCDD (D75), PeCDF (F114), TCDF (F83), HxCDF (F130), HpCDF (F131), HxCDF (F121), HpCDF (F134), HxCDF (F124), OCDF (F135), PeCDF (F94), HxCDF (F118), Sum dioksiner-TEQ (PCDD + PCDF) og dioksinlignende stoffer-TEQ (PCB-DL)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Polysykliske aromatiske hydrokarboner (PAH)</td>
<td style="text-align: left;">Fluoranten, Indeno[1,2,3-cd]pyren, Naftalen, Antracen, Benzo[a]pyren, Benzo[b]fluoranten, Benzo[ghi]perylen, Benzo[k]fluoranten</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tinnorganiske forbindelser (TIN)</td>
<td style="text-align: left;">Tributyltinn kation (TBT)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>To be honest, I don’t know enough about monitoring campaigns to make a good judgement about this data. The pesticides (under OCL), PCBs, PAHs, and heavy metals look right to me. I don’t know whether these substances are prioritised at the EU level or more locally (national or e.g. river basin).</p>
</section></section><section class="section level2"><h2 id="horizontal-slice">Horizontal Slice<a class="anchor" aria-label="anchor" href="#horizontal-slice"></a>
</h2>
<p>To gain a deeper understanding about the patterns of pollutants in Vannmiljø, we need to work with actual measurements.</p>
<p>Let’s start with a horizontal slice of Vannmiljø, hopefully more-or-less representative. This is all the data from 01 January 2020 to 31 May 2020, which is 464,059 rows. This is downloaded from <code>Søk i vannrelaterte data</code>, so we can expect not only pollutants (chemicals, microplastics, etc.), but also biological quality parameters,</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">horizontal_slice</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://arrow.apache.org/docs/r/reference/read_parquet.html" class="external-link">read_parquet</a></span><span class="op">(</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html" class="external-link">here</a></span><span class="op">(</span></span>
<span>  <span class="st">"inst"</span>,</span>
<span>  <span class="st">"example_datasets"</span>,</span>
<span>  <span class="st">"registrations"</span>,</span>
<span>  <span class="st">"WaterRegistrationExport-NO-Jan20-May20.parquet"</span></span>
<span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">pollutant_representation</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html" class="external-link">right_join</a></span><span class="op">(</span></span>
<span>  <span class="va">horizontal_slice</span>,</span>
<span>  <span class="va">pollutants</span>,</span>
<span>  by <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/join_by.html" class="external-link">join_by</a></span><span class="op">(</span><span class="va">Parameter_id</span> <span class="op">==</span> <span class="va">ParameterID</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html" class="external-link">glimpse</a></span><span class="op">(</span><span class="va">pollutant_representation</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Rows: 75,320
Columns: 48
$ Vannlokalitet_kode    &lt;chr&gt; "053-27554", "053-27554", "053-27554", "053-2755…
$ Vannlokalitetsnavn    &lt;chr&gt; "Gjønavatnet", "Gjønavatnet", "Gjønavatnet", "Gj…
$ Betegnelse            &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ Type                  &lt;chr&gt; "Innsjø", "Innsjø", "Innsjø", "Innsjø", "Innsjø"…
$ Aktivitet_id          &lt;chr&gt; "TILT", "TILT", "TILT", "TILT", "TILT", "TILT", …
$ Aktivitet_navn        &lt;chr&gt; "Tiltaksorientert overvåking", "Tiltaksorientert…
$ Oppdragsgiver         &lt;chr&gt; "Oppdrettere", "Oppdrettere", "Oppdrettere", "Op…
$ Oppdragstaker         &lt;chr&gt; "Rådgivende Biologer AS", "Rådgivende Biologer A…
$ Parameter_id          &lt;chr&gt; "CD", "CU", "ZN", "FE", "CD", "CU", "ZN", "FE", …
$ Parameter_navn        &lt;chr&gt; "Kadmium", "Kobber", "Sink", "Jern", "Kadmium", …
$ Parameter_casnr       &lt;chr&gt; "7440-43-9", "7440-50-8", "7440-66-6", "7439-89-…
$ Medium_id             &lt;chr&gt; "VF", "VF", "VF", "VF", "VF", "VF", "VF", "VF", …
$ Medium_navn           &lt;chr&gt; "Ferskvann", "Ferskvann", "Ferskvann", "Ferskvan…
$ LatinskNavn_id        &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ VitenskapligNavn      &lt;chr&gt; "Artsuavhengig", "Artsuavhengig", "Artsuavhengig…
$ Provetakmetode_id     &lt;chr&gt; "NS-ISO 5667-4:2016A", "NS-ISO 5667-4:2016A", "N…
$ Analysemetode_id      &lt;chr&gt; "NS-EN ISO 17294-2:2016", "NS-EN ISO 17294-2:201…
$ Tid_provetak          &lt;chr&gt; "2020-04-22 00:00:00", "2020-04-22 00:00:00", "2…
$ Ovre_dyp              &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ Nedre_dyp             &lt;dbl&gt; 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, …
$ DybdeEnhet            &lt;chr&gt; "m", "m", "m", "m", "m", "m", "m", "m", "m", "m"…
$ Filtrert_Prove        &lt;chr&gt; "Ufiltrert", "Ufiltrert", "Ufiltrert", "Ufiltrer…
$ UnntasKlassifisering  &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ Operator              &lt;chr&gt; "=", "=", "=", "=", "=", "=", "=", "=", "=", "="…
$ Verdi                 &lt;dbl&gt; 0.009, 0.160, 1.200, 12.000, 0.011, 0.170, 1.300…
$ Listenavn             &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ Enhet                 &lt;chr&gt; "µg/l", "µg/l", "µg/l", "µg/l", "µg/l", "µg/l", …
$ Provenr               &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ Deteksjonsgrense      &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ Kvantifiseringsgrense &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ Opprinnelse           &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ Ant_verdier           &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ Kommentar             &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ Arkiv                 &lt;chr&gt; "N", "N", "N", "N", "N", "N", "N", "N", "N", "N"…
$ Produktbeskrivelse    &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ `UTM33 Ost (X)`       &lt;dbl&gt; -5393.856, -5393.856, -5393.856, -5393.856, -539…
$ `UTM33 Nord (Y)`      &lt;dbl&gt; 6715392, 6715392, 6715392, 6715392, 6715392, 671…
$ Name                  &lt;chr&gt; "Kadmium", "Kobber", "Sink", "Jern", "Kadmium", …
$ Description           &lt;chr&gt; "Kadmium", "Kobber", "Sink", "Jern", "Kadmium", …
$ CASnr                 &lt;chr&gt; "7440-43-9", "7440-50-8", "7440-66-6", "7439-89-…
$ QualityElementTypeID  &lt;chr&gt; "SFS", "SFS", "SFS", "SFS", "SFS", "SFS", "SFS",…
$ QualityElementID      &lt;chr&gt; "PRI", "AST", "AST", "AST", "PRI", "AST", "AST",…
$ QualityElementName    &lt;chr&gt; "Prioriterte stoffer", "Andre stoffer", "Andre s…
$ SubGroupID            &lt;chr&gt; "MET", "MET", "MET", "MET", "MET", "MET", "MET",…
$ SubGroupName          &lt;chr&gt; "Metaller (MET)", "Metaller (MET)", "Metaller (M…
$ ParameterID_VannNett  &lt;chr&gt; "CAS_7440-43-9", "CAS_7440-50-8", "CAS_7440-66-6…
$ ParameterID_WISE      &lt;chr&gt; "CAS_7440-43-9", "CAS_7440-50-8", "CAS_7440-66-6…
$ Prioritized           &lt;chr&gt; "P", NA, NA, NA, "P", NA, NA, NA, NA, NA, NA, NA…</code></pre>
</div>
</div>
<p>First, most important note. Right-joining to pollutants leaves us with 75,320 rows, less than a quarter of the original data.</p>
<p>Which subgroups are best represented?</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">pollutant_rep_per_subgroup</span> <span class="op">&lt;-</span> <span class="va">pollutant_representation</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html" class="external-link">group_by</a></span><span class="op">(</span><span class="va">QualityElementName</span>, <span class="va">SubGroupName</span>, <span class="va">SubGroupID</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/reframe.html" class="external-link">reframe</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html" class="external-link">n</a></span><span class="op">(</span><span class="op">)</span>, n_substances <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/n_distinct.html" class="external-link">n_distinct</a></span><span class="op">(</span><span class="va">Parameter_id</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html" class="external-link">mutate</a></span><span class="op">(</span></span>
<span>    SubGroupName <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_reorder.html" class="external-link">fct_reorder</a></span><span class="op">(</span><span class="va">SubGroupName</span>, <span class="va">n</span>, .fun <span class="op">=</span> <span class="va">sum</span>, .na_rm <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html" class="external-link">ggplot</a></span><span class="op">(</span></span>
<span>  <span class="va">pollutant_rep_per_subgroup</span>,</span>
<span>  mapping <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html" class="external-link">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">SubGroupName</span>, x <span class="op">=</span> <span class="va">n</span>, fill <span class="op">=</span> <span class="va">QualityElementName</span><span class="op">)</span></span>
<span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html" class="external-link">geom_col</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html" class="external-link">labs</a></span><span class="op">(</span>subtitle <span class="op">=</span> <span class="st">"Horizontal slice, all compartments"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html" class="external-link">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"bottom"</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<div>
<figure><p><a href="vannmiljo-pollutants_files/figure-html/unnamed-chunk-3-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="vannmiljo-pollutants_files/figure-html/unnamed-chunk-3-1.png" width="672"></a></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">pareto</span> <span class="op">&lt;-</span> <span class="va">pollutant_rep_per_subgroup</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html" class="external-link">mutate</a></span><span class="op">(</span></span>
<span>    is_main_subgroups <span class="op">=</span> <span class="va">SubGroupID</span> <span class="op"><a href="https://rdrr.io/r/base/match.html" class="external-link">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"MET"</span>, <span class="st">"PAH"</span>, <span class="st">"ORG"</span>, <span class="st">"PFAS"</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/reframe.html" class="external-link">reframe</a></span><span class="op">(</span>sum_n <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html" class="external-link">sum</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span>, .by <span class="op">=</span> <span class="va">is_main_subgroups</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html" class="external-link">pull</a></span><span class="op">(</span><span class="va">pareto</span>, <span class="va">sum_n</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span> <span class="op">/</span> <span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html" class="external-link">pull</a></span><span class="op">(</span><span class="va">pareto</span>, <span class="va">sum_n</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">+</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html" class="external-link">pull</a></span><span class="op">(</span><span class="va">pareto</span>, <span class="va">sum_n</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.756957</code></pre>
</div>
</div>
<p>So:</p>
<ul>
<li>Prioritised substances are overrepresented (which makes a lot of sense), but still less than half of total measured data</li>
<li>Metals, PAHs, organic molecules, and PFAS are by far the most measured groups (a little over 75%)</li>
</ul>
<section class="level2"><h3 id="pollutants-in-salt-water-and-sediment">Pollutants in Salt water and sediment<a class="anchor" aria-label="anchor" href="#pollutants-in-salt-water-and-sediment"></a>
</h3>
<p>One key obstacle to using the above data is that we don’t know if what we’re seeing is a representative sample of the parts of Vannmiljø we’re interested in - marine water and sediment. So we should subset our slice and take a closer look.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">horizontal_slice_salt</span> <span class="op">&lt;-</span> <span class="va">horizontal_slice</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">Medium_id</span> <span class="op"><a href="https://rdrr.io/r/base/match.html" class="external-link">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"VS"</span>, <span class="st">"SS"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html" class="external-link">nrow</a></span><span class="op">(</span><span class="va">horizontal_slice</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 464059</code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html" class="external-link">nrow</a></span><span class="op">(</span><span class="va">horizontal_slice_salt</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 295430</code></pre>
</div>
</div>
<p>In doing so, we reduce our slice from 464,059 to 295,430 rows. Then more or less the same operation as above:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">pollutant_representation_salt</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html" class="external-link">right_join</a></span><span class="op">(</span></span>
<span>  <span class="va">horizontal_slice_salt</span>,</span>
<span>  <span class="va">pollutants</span>,</span>
<span>  by <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/join_by.html" class="external-link">join_by</a></span><span class="op">(</span><span class="va">Parameter_id</span> <span class="op">==</span> <span class="va">ParameterID</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">pollutant_rep_per_subgroup_salt</span> <span class="op">&lt;-</span> <span class="va">pollutant_representation_salt</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html" class="external-link">group_by</a></span><span class="op">(</span><span class="va">QualityElementName</span>, <span class="va">SubGroupName</span>, <span class="va">SubGroupID</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/reframe.html" class="external-link">reframe</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html" class="external-link">n</a></span><span class="op">(</span><span class="op">)</span>, n_substances <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/n_distinct.html" class="external-link">n_distinct</a></span><span class="op">(</span><span class="va">Parameter_id</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html" class="external-link">mutate</a></span><span class="op">(</span></span>
<span>    SubGroupName <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_reorder.html" class="external-link">fct_reorder</a></span><span class="op">(</span><span class="va">SubGroupName</span>, <span class="va">n</span>, .fun <span class="op">=</span> <span class="va">sum</span>, .na_rm <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html" class="external-link">ggplot</a></span><span class="op">(</span></span>
<span>  <span class="va">pollutant_rep_per_subgroup_salt</span>,</span>
<span>  mapping <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html" class="external-link">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">SubGroupName</span>, x <span class="op">=</span> <span class="va">n</span>, fill <span class="op">=</span> <span class="va">QualityElementName</span><span class="op">)</span></span>
<span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html" class="external-link">geom_col</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html" class="external-link">labs</a></span><span class="op">(</span>subtitle <span class="op">=</span> <span class="st">"Horizontal slice, Salt water/sediment subset"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html" class="external-link">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"bottom"</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<div>
<figure><p><a href="vannmiljo-pollutants_files/figure-html/unnamed-chunk-6-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="vannmiljo-pollutants_files/figure-html/unnamed-chunk-6-1.png" width="672"></a></p>
</figure>
</div>
</div>
</div>
<p>So, in some places the pattern holds. Metals are still the best represented, and PAH are still in position #2. Priority substances are still less than half of all groups. Our x axis goes from a limit of 30,000 to 6,000</p>
<p>Key differences: - ORG drops from #3 to #4 - PCBs rises from #5 to #3 - PFAS drops from #4 to #5 - Tinorganic molecules rises to #6</p>
</section></section><section class="section level2"><h2 id="individual-stressors">Individual Stressors<a class="anchor" aria-label="anchor" href="#individual-stressors"></a>
</h2>
<p>We should look at individual stressors too. Rather than work with too large a dataset, we’ll continue with the salt (salt water, and salt water sediment) subset of the horizontal slice.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">salt_pollutant_overview</span> <span class="op">&lt;-</span> <span class="va">pollutant_representation_salt</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html" class="external-link">group_by</a></span><span class="op">(</span></span>
<span>    <span class="va">Parameter_id</span>,</span>
<span>    <span class="va">Parameter_navn</span>,</span>
<span>    <span class="va">SubGroupID</span>,</span>
<span>    <span class="va">SubGroupName</span>,</span>
<span>    <span class="va">Aktivitet_id</span>,</span>
<span>    <span class="va">Aktivitet_navn</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/reframe.html" class="external-link">reframe</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html" class="external-link">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html" class="external-link">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html" class="external-link">desc</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">top_salt_pollutants</span> <span class="op">&lt;-</span> <span class="va">salt_pollutant_overview</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html" class="external-link">slice_max</a></span><span class="op">(</span>order_by <span class="op">=</span> <span class="va">n</span>, prop <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Fix the activity levels (ordered by overall size) and the colour for each, so</span></span>
<span><span class="co"># an activity looks the same in every plot, even where it is absent. Levels come</span></span>
<span><span class="co"># from the top-10% subset actually plotted, not the full overview (13 values).</span></span>
<span><span class="va">activity_levels</span> <span class="op">&lt;-</span> <span class="va">top_salt_pollutants</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html" class="external-link">count</a></span><span class="op">(</span><span class="va">Aktivitet_navn</span>, wt <span class="op">=</span> <span class="va">n</span>, sort <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html" class="external-link">pull</a></span><span class="op">(</span><span class="va">Aktivitet_navn</span><span class="op">)</span></span>
<span></span>
<span><span class="va">activity_colours</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rlang.r-lib.org/reference/set_names.html" class="external-link">set_names</a></span><span class="op">(</span></span>
<span>  <span class="fu">RColorBrewer</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/RColorBrewer/man/ColorBrewer.html" class="external-link">brewer.pal</a></span><span class="op">(</span><span class="fl">12</span>, <span class="st">"Paired"</span><span class="op">)</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html" class="external-link">seq_along</a></span><span class="op">(</span><span class="va">activity_levels</span><span class="op">)</span><span class="op">]</span>,</span>
<span>  <span class="va">activity_levels</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">plot_subgroup</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">data</span>, <span class="va">subgroup</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">data</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html" class="external-link">mutate</a></span><span class="op">(</span>Parameter_id <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_reorder.html" class="external-link">fct_reorder</a></span><span class="op">(</span><span class="va">Parameter_id</span>, <span class="va">n</span>, .fun <span class="op">=</span> <span class="va">sum</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html" class="external-link">ggplot</a></span><span class="op">(</span>mapping <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html" class="external-link">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">Parameter_id</span>, x <span class="op">=</span> <span class="va">n</span>, fill <span class="op">=</span> <span class="va">Aktivitet_navn</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html" class="external-link">geom_col</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html" class="external-link">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="va">activity_colours</span>, drop <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/guides.html" class="external-link">guides</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/guide_legend.html" class="external-link">guide_legend</a></span><span class="op">(</span>nrow <span class="op">=</span> <span class="fl">4</span>, title <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html" class="external-link">theme_minimal</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html" class="external-link">theme</a></span><span class="op">(</span></span>
<span>      legend.position <span class="op">=</span> <span class="st">"bottom"</span>,</span>
<span>      legend.text <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html" class="external-link">element_text</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">7</span><span class="op">)</span>,</span>
<span>      legend.key.size <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grid/unit.html" class="external-link">unit</a></span><span class="op">(</span><span class="fl">0.35</span>, <span class="st">"cm"</span><span class="op">)</span>,</span>
<span>      panel.grid.major.y <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html" class="external-link">element_blank</a></span><span class="op">(</span><span class="op">)</span></span>
<span>    <span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html" class="external-link">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="va">subgroup</span>, x <span class="op">=</span> <span class="st">"Samples"</span>, y <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="va">subgroup_plots</span> <span class="op">&lt;-</span> <span class="va">top_salt_pollutants</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html" class="external-link">mutate</a></span><span class="op">(</span>Aktivitet_navn <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html" class="external-link">factor</a></span><span class="op">(</span><span class="va">Aktivitet_navn</span>, levels <span class="op">=</span> <span class="va">activity_levels</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/split.html" class="external-link">split</a></span><span class="op">(</span><span class="op">~</span><span class="va">SubGroupID</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://purrr.tidyverse.org/reference/map.html" class="external-link">map</a></span><span class="op">(</span>\<span class="op">(</span><span class="va">d</span><span class="op">)</span> <span class="fu">plot_subgroup</span><span class="op">(</span><span class="va">d</span>, <span class="fu"><a href="https://rdrr.io/r/base/unique.html" class="external-link">unique</a></span><span class="op">(</span><span class="va">d</span><span class="op">$</span><span class="va">SubGroupName</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
</details>
</div>
<p>Saltwater/sediment pollutant sample counts by subgroup and activity (horizontal slice, stressors filtered to top 10% by sample size). Subgroups available: BDE, MET, ORG, PAH, PCB, PFA, TIN.</p>
<p>What are the most important takeaways here:</p>
<section class="level3"><h4 id="metals">Metals<a class="anchor" aria-label="anchor" href="#metals"></a>
</h4>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">subgroup_plots</span><span class="op">[[</span><span class="st">"MET"</span><span class="op">]</span><span class="op">]</span></span></code></pre></div>
</details><div class="cell-output-display">
<div>
<figure><p><a href="vannmiljo-pollutants_files/figure-html/unnamed-chunk-8-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="vannmiljo-pollutants_files/figure-html/unnamed-chunk-8-1.png" width="672"></a></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li>Aquaculture monitoring is the single biggest source of <em>copper</em> and <em>zinc</em> data, and also provides a handful of <em>cadmium</em> data. It does not report on any other stressors (although we might expect it to include tralopyril data if we looked at a more recent year, as this has <a href="https://www.miljodirektoratet.no/ansvarsomrader/kjemikalier/biocider/biocider-i-notimpregnering/" class="external-link">largely displaced copper-based net antifoulants</a>).</li>
<li>Beyond this, Marine grunnkart is kystsonen is the next biggest source. Overvåkning av pårvirkning fra industri, forurenset sjøbunn, and tiltaksorientert overvåking are also important sources of data.</li>
</ol></section><section class="level3"><h4 id="organic-molecules">Organic Molecules<a class="anchor" aria-label="anchor" href="#organic-molecules"></a>
</h4>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">subgroup_plots</span><span class="op">[[</span><span class="st">"ORG"</span><span class="op">]</span><span class="op">]</span></span></code></pre></div>
</details><div class="cell-output-display">
<div>
<figure><p><a href="vannmiljo-pollutants_files/figure-html/unnamed-chunk-9-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img src="vannmiljo-pollutants_files/figure-html/unnamed-chunk-9-1.png" width="672"></a></p>
</figure>
</div>
</div>
</div>
<ul>
<li>A handful of these are measured by Problemkartlegging, Overvåkning av pårvirkning fra industri, and Overvåkning av pårvirkning fra flyplass. However, the sample sizes are very small compared to metals.</li>
</ul></section><section class="level3"><h4 id="pfas">PFAS<a class="anchor" aria-label="anchor" href="#pfas"></a>
</h4>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">subgroup_plots</span><span class="op">[[</span><span class="st">"PFA"</span><span class="op">]</span><span class="op">]</span></span></code></pre></div>
</details><div class="cell-output-display">
<div>
<figure><p><a href="vannmiljo-pollutants_files/figure-html/unnamed-chunk-10-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5"><img src="vannmiljo-pollutants_files/figure-html/unnamed-chunk-10-1.png" width="672"></a></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Entirely measured by Overvåkning av pårvirkning fra industri, except for SPFAS, which is <em>flyplass</em> (presumably a firefighting foam)</li>
<li>Very small sample sizes, but consistent (PFAS 25, or something?). There’s a more or less standard battery of PFAS.</li>
</ul></section><section class="level3"><h4 id="pbde">PBDE<a class="anchor" aria-label="anchor" href="#pbde"></a>
</h4>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">subgroup_plots</span><span class="op">[[</span><span class="st">"BDE"</span><span class="op">]</span><span class="op">]</span></span></code></pre></div>
</details><div class="cell-output-display">
<div>
<figure><p><a href="vannmiljo-pollutants_files/figure-html/unnamed-chunk-11-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6"><img src="vannmiljo-pollutants_files/figure-html/unnamed-chunk-11-1.png" width="672"></a></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Overvåkning av forurenset sjøbunn only, four PBDE, 20 samples.</li>
</ul></section><section class="level3"><h4 id="pcb">PCB<a class="anchor" aria-label="anchor" href="#pcb"></a>
</h4>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">subgroup_plots</span><span class="op">[[</span><span class="st">"PCB"</span><span class="op">]</span><span class="op">]</span></span></code></pre></div>
</details><div class="cell-output-display">
<div>
<figure><p><a href="vannmiljo-pollutants_files/figure-html/unnamed-chunk-12-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7"><img src="vannmiljo-pollutants_files/figure-html/unnamed-chunk-12-1.png" width="672"></a></p>
</figure>
</div>
</div>
</div>
<ul>
<li>A mixture of <code>Overvåkning av forurenset sjøbunn only</code>, <code>Tiltaksorientert overvåking</code>, <code>Effekter av mudring, utffylling og dumping</code>, <code>Problemkartlegging</code>, and a handful of others.</li>
<li>Looks like a standardised battery of 8 substances.</li>
</ul></section><section class="level3"><h4 id="pahs">PAHs<a class="anchor" aria-label="anchor" href="#pahs"></a>
</h4>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">subgroup_plots</span><span class="op">[[</span><span class="st">"PAH"</span><span class="op">]</span><span class="op">]</span></span></code></pre></div>
</details><div class="cell-output-display">
<div>
<figure><p><a href="vannmiljo-pollutants_files/figure-html/unnamed-chunk-13-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8"><img src="vannmiljo-pollutants_files/figure-html/unnamed-chunk-13-1.png" width="672"></a></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Decently big sample sizes for the majority of substances</li>
<li>A set of 12 standard PAH, two almost as standard, and then a mixed bag of several monitored less consistently</li>
</ul></section><section class="level3"><h4 id="tinorganic-molcules">Tinorganic Molcules<a class="anchor" aria-label="anchor" href="#tinorganic-molcules"></a>
</h4>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">subgroup_plots</span><span class="op">[[</span><span class="st">"TIN"</span><span class="op">]</span><span class="op">]</span></span></code></pre></div>
</details><div class="cell-output-display">
<div>
<figure><p><a href="vannmiljo-pollutants_files/figure-html/unnamed-chunk-14-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9"><img src="vannmiljo-pollutants_files/figure-html/unnamed-chunk-14-1.png" width="672"></a></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Basically, TBSN+ (most sampled), MBSN+, and DBSN+, with n = 100 - 150</li>
<li>These are from <code>Overvåkning av forurenset sjøbunn</code>, <code>Tiltaksorientert overvåking</code>, <code>Effekter av mudring...</code> and a handful of others.</li>
</ul></section></section><section class="section level2"><h2 id="conclusions">Conclusions<a class="anchor" aria-label="anchor" href="#conclusions"></a>
</h2>
<p>In the available data: - Metals are by far the most monitored. The over-representation of copper and zinc is largely driven by aquaculture monitoring - PFAS are measured entirely by Industry monitoring - Contaminated sea bed is an important contributor of PAH, Tin-organic, PDBE, and PDBE data (though measured-oriented monotiring, effects of dredging, industry monitoring, problem survey, and other) are also noteworthy contributors - In general, the distribution of different stressors in different campaigns is difficult to predict just from the names/descriptions of these campaigns. - In this dataset Milkys and MAREANO aren’t represented at all, which is surprising as I would expect them to be important contributors to marine pollution data (probably an artefact of the time period selected)</p>
</section><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      }
    });

    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });

  };

})();
          </script></main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside>
</div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by Sam Welch.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.2.1.</p>
</div>

    </footer>
</div>





  </body>
</html>
